Add baas-network-tests nightly task for testing sync client operation with non-ideal network conditions (#6852)
* Added support for starting baas proxy
* Fixed some issues when running the scripts
* minor updates to install_baas.sh
* Updates to scripts to run on evergreen spawn host
* Added total time output to object store tests
* Increased initial ssh connect attempts; renamed proxy to 'baas_proxy'
* Minor updates to help output
* Added baas network test to run bass with the proxy
* Added support for separate baas admin api url value
* Minor port check adjustments
* Removed 'compile' task from network_tests
* Disable development mode by default
* Added baas remote host and network tests instructions doc
* Minor updates to the instructions
* Minor updates to documentation

diff --git a/evergreen/config.yml b/evergreen/config.yml
--- a/evergreen/config.yml
+++ b/evergreen/config.yml
@@ -75,8 +75,12 @@ functions:
           fi
 
           if [ -z "${disable_tests_against_baas|}" ]; then
+              scheme="http"
               set_cmake_var baas_vars REALM_ENABLE_AUTH_TESTS BOOL On
-              set_cmake_var baas_vars REALM_MONGODB_ENDPOINT STRING "http://localhost:9090"
+              set_cmake_var baas_vars REALM_MONGODB_ENDPOINT STRING "$scheme://localhost:9090"
+              if [ -n "${baas_admin_port|}" ]; then
+                set_cmake_var baas_vars REALM_ADMIN_ENDPOINT STRING "$scheme://localhost:${baas_admin_port}"
+              fi
           fi
 
           if [ -n "${enable_asan|}" ]; then
@@ -132,7 +136,7 @@ functions:
           fi
 
           set_cmake_var realm_vars REALM_TEST_LOGGING BOOL On
-          set_cmake_var realm_vars REALM_TEST_LOGGING_LEVEL STRING "debug"
+          set_cmake_var realm_vars REALM_TEST_LOGGING_LEVEL STRING "${test_logging_level|debug}"
 
           GENERATOR="${cmake_generator}"
           if [ -z "${cmake_generator|}" ]; then
@@ -274,6 +278,8 @@ functions:
   - command: attach.results
     params:
       file_location: realm-core/${task_name}_results.json
+
+  "upload baas artifacts":
   - command: shell.exec
     params:
       working_dir: realm-core
@@ -289,7 +295,7 @@ functions:
 
         # Copy the baas_server log from the remote baas host if it exists
         if [[ ! -f baas_host.yml || ! -f .baas_ssh_key ]]; then
-          echo "No remote baas host or remote baas host definitions not found"
+          echo "Skipping - no remote baas host or remote baas host definitions not found"
           exit
         fi
 
@@ -299,14 +305,22 @@ functions:
         ssh_user="$(printf "ubuntu@%s" "$BAAS_HOST_NAME")"
         ssh_options="-o ForwardAgent=yes -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o ConnectTimeout=60 -i .baas_ssh_key"
 
-        # Copy the baas_server.log and mongod.log files from the remote baas host
-        REMOTE_PATH=/data/baas-remote/baas-work-dir
-        LOCAL_PATH=./baas-work-dir
+        # Copy the baas_server.log, mongod.log and (optionally) baas_proxy.log files from the remote baas host
+        REMOTE_PATH=/data/baas-remote
+        REMOTE_BAAS_PATH="$REMOTE_PATH/baas-work-dir"
+        REMOTE_BAAS_DB_PATH="$REMOTE_BAAS_PATH/mongodb-dbpath"
+        REMOTE_PROXY_PATH="$REMOTE_PATH/baas-proxy-dir"
 
-        mkdir -p "$LOCAL_PATH/"
-        mkdir -p "$LOCAL_PATH/mongodb-dbpath/"
-        scp $ssh_options $ssh_user:"$REMOTE_PATH/baas_server.log" "$LOCAL_PATH/baas_server.log" || true
-        scp $ssh_options $ssh_user:"$REMOTE_PATH/mongodb-dbpath/mongod.log" "$LOCAL_PATH/mongodb-dbpath/mongod.log" || true
+        LOCAL_BAAS_PATH=./baas-work-dir
+        LOCAL_BAAS_DB_PATH="$LOCAL_BAAS_PATH/mongodb-dbpath"
+        LOCAL_PROXY_PATH=./baas-proxy-dir
+
+        mkdir -p "$LOCAL_BAAS_PATH/"
+        mkdir -p "$LOCAL_BAAS_DB_PATH/"
+        mkdir -p "$LOCAL_PROXY_PATH/"
+        scp $ssh_options $ssh_user:"$REMOTE_BAAS_PATH/baas_server.log" "$LOCAL_BAAS_PATH/baas_server.log" || true
+        scp $ssh_options $ssh_user:"$REMOTE_BAAS_DB_PATH/mongod.log" "$LOCAL_BAAS_DB_PATH/mongod.log" || true
+        scp $ssh_options $ssh_user:"$REMOTE_PROXY_PATH/baas_proxy.log" "$LOCAL_PROXY_PATH/baas_proxy.log" || true
 
   - command: s3.put
     params:
@@ -340,6 +354,17 @@ functions:
       permissions: public-read
       content_type: text/text
       display_name: mongod logs
+      optional: true
+  - command: s3.put
+    params:
+      aws_key: '${artifacts_aws_access_key}'
+      aws_secret: '${artifacts_aws_secret_key}'
+      local_file: 'realm-core/baas-proxy-dir/baas_proxy.log'
+      remote_file: 'realm-core-stable/${branch_name}/${task_id}/${execution}/baas_proxy.log'
+      bucket: mciuploads
+      permissions: public-read
+      content_type: text/text
+      display_name: baas proxy logs
       optional: true
 
   "upload fuzzer results":
@@ -532,13 +557,23 @@ functions:
         BAAS_USER=ubuntu
 
         OPT_BAAS_BRANCH=
+        OPT_BAAS_PROXY=
+        OPT_BAAS_DIRECT=
+
         if [ -n "${baas_branch}" ]; then
             OPT_BAAS_BRANCH="-b ${baas_branch}"
+        fi
+        if [ -n "${baas_proxy}" ]; then
+            OPT_BAAS_PROXY="-t"
+            if [ -n "${baas_admin_port}" ]; then
+                OPT_BAAS_DIRECT="-d ${baas_admin_port}"
+            fi
         fi
 
         # Run the setup_baas_host_local.sh script to configure and run baas on the remote host
         # Add -v to this command for verbose script logging
-        ./evergreen/setup_baas_host_local.sh -w ./baas-work-dir -u $BAAS_USER $OPT_BAAS_BRANCH ./baas_host_vars.sh ./.baas_ssh_key 2>&1 | tee install_baas_output.log
+        ./evergreen/setup_baas_host_local.sh -w ./baas-work-dir -u $BAAS_USER $OPT_BAAS_BRANCH $OPT_BAAS_PROXY \
+            $OPT_BAAS_DIRECT ./baas_host_vars.sh ./.baas_ssh_key 2>&1 | tee install_baas_output.log
 
   "wait for baas to start":
   - command: shell.exec
@@ -842,7 +877,7 @@ tasks:
 
 # These are local object store tests; baas is not started, however some use the sync server
 - name: object-store-tests
-  tags: [ "test_suite_remote_baas", "for_pull_requests" ]
+  tags: [ "object_store_test_suite", "for_pull_requests" ]
   exec_timeout_secs: 3600
   commands:
   - func: "compile"
@@ -857,12 +892,31 @@ tasks:
 
 # These are baas object store tests that run against baas running on a remote host
 - name: baas-integration-tests
-  tags: [ "test_suite_remote_baas", "for_pull_requests" ]
+  tags: [ "object_store_test_suite", "for_pull_requests" ]
   exec_timeout_secs: 3600
   commands:
   - func: "launch remote baas"
     vars:
-      baas_branch: 3f31617aacfe5d31b9057fc298b735b60acd6424
+      baas_branch: master
+  - func: "compile"
+    vars:
+      target_to_build: ObjectStoreTests
+  - func: "wait for baas to start"
+  - func: "run tests"
+    vars:
+      test_label: objstore-baas
+      test_executable_name: "realm-object-store-tests"
+      verbose_test_output: true
+  - func: "check branch state"
+
+- name: baas-network-tests
+  tags: [ "for_nightly_tests" ]
+  exec_timeout_secs: 14400
+  commands:
+  - func: "launch remote baas"
+    vars:
+      baas_branch: master
+      baas_proxy: On
   - func: "compile"
     vars:
       target_to_build: ObjectStoreTests
@@ -1043,12 +1097,13 @@ task_groups:
   - func: "fetch binaries"
   teardown_task:
   - func: "upload test results"
+  - func: "upload baas artifacts"
   timeout:
   - func: "run hang analyzer"
   tasks:
   - compile
   - .test_suite
-  - .test_suite_remote_baas
+  - .object_store_test_suite
   - package
 
 # Runs object-store-tests against baas running on remote host
@@ -1060,12 +1115,29 @@ task_groups:
   - func: "fetch binaries"
   teardown_task:
   - func: "upload test results"
+  - func: "upload baas artifacts"
   timeout:
   - func: "run hang analyzer"
   tasks:
   - compile
   - .test_suite
-  - .test_suite_remote_baas
+  - .object_store_test_suite
+
+# Runs object-store-tests against baas running on remote host and runs
+# the network simulation tests as a separate task for nightly builds
+- name: network_tests
+  max_hosts: 1
+  setup_group_can_fail_task: true
+  setup_group:
+  - func: "fetch source"
+  - func: "fetch binaries"
+  teardown_task:
+  - func: "upload test results"
+  - func: "upload baas artifacts"
+  timeout:
+  - func: "run hang analyzer"
+  tasks:
+  - baas-network-tests
 
 # Runs object-store-tests against baas running on remote host
 - name: compile_test_coverage
@@ -1076,12 +1148,13 @@ task_groups:
   - func: "fetch binaries"
   teardown_task:
   - func: "upload test results"
+  - func: "upload baas artifacts"
   timeout:
   - func: "run hang analyzer"
   tasks:
   - compile
   - .test_suite
-  - .test_suite_remote_baas
+  - .object_store_test_suite
   - process_coverage_data
 
 - name: benchmarks
@@ -1297,6 +1370,24 @@ buildvariants:
   - name: fuzzer-tests
     activate: false
 
+- name: ubuntu2004-network
+  display_name: "Ubuntu 20.04 x86_64 (Clang 11 Baas network tests)"
+  run_on: ubuntu2004-large
+  expansions:
+    clang_url: "https://s3.amazonaws.com/static.realm.io/evergreen-assets/clang%2Bllvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz"
+    cmake_url: "https://s3.amazonaws.com/static.realm.io/evergreen-assets/cmake-3.20.3-linux-x86_64.tar.gz"
+    cmake_bindir: "./cmake_binaries/bin"
+    fetch_missing_dependencies: On
+    c_compiler: "./clang_binaries/bin/clang"
+    cxx_compiler: "./clang_binaries/bin/clang++"
+    cmake_build_type: RelWithDebInfo
+    run_with_encryption: On
+    baas_admin_port: 9098
+    test_logging_level: trace
+  tasks:
+  - name: network_tests
+    activate: true
+
 - name: rhel70
   display_name: "RHEL 7 x86_64"
   run_on: rhel70-large
@@ -1467,8 +1558,7 @@ buildvariants:
     curl_base: "/cygdrive/c/curl"
     python3: "/cygdrive/c/python/python37/python.exe"
   tasks:
-  - name: compile_test_and_package
-  - name: long-running-tests
+  - name: compile_test
 
 - name: windows-64-encryption
   display_name: "Windows x86_64 (Encryption enabled)"
@@ -1500,4 +1590,5 @@ buildvariants:
     curl_base: "/cygdrive/c/curl"
     python3: "/cygdrive/c/python/python37/python.exe"
   tasks:
-  - name: compile_test
+  - name: compile_test_and_package
+  - name: long-running-tests
